### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Winters123** [Bestduan/fpga_support_plug#15]
- Issue Type: `Performance`
- Extension Name: `fpga-support`
- Extension Version: `0.1.15`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.56.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\ADMINI~1\AppData\Local\Temp\sterben.fpga-support-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by Bestduan** [comment]
Thanks for your advice, I have found out the reasons for the high CPU consumption. There are mainly two aspects, one is the HDL syntax check, which causes CPU consumption under multiple files, the other is the execution of the exec function of the regular expression in NodeJS is stuck, so I have to admit that the performance of the regular expression in JS is not very ideal.This will be fixed in a later release.

**Comment by Winters123** [comment]
I see. Thanks for your reply.
